---
# tasks file for docker
 - name: create docker image
   docker_image:
      name: mariemmnijli/livraison-continue:LC
      build:
         path: /var/lib/jenkins/workspace/LC                 
         pull: no
      source: build
      state: present
      force_source: true
 - name: run docker container
   docker_container:
      name: mayapp-container
      image: mariemmnijli/livraison-continue:LC
      state: started
      recreate: true
      ports:
        - "4200:80"
